# Generated by Django 5.2.17 on 2026-08-24 06:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_code', models.SlugField(max_length=32, unique=True)),
                ('db_name', models.CharField(max_length=63, unique=True)),
                ('db_user', models.CharField(blank=True, max_length=63)),
                ('db_host', models.CharField(default='localhost', max_length=255)),
                ('db_port', models.PositiveIntegerField(default=5432)),
                ('fineract_tenant_identifier', models.CharField(max_length=63, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROVISIONING', 'Provisioning'), ('INITIALIZING', 'Initializing'), ('READY', 'Ready'), ('FAILED', 'Failed'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=16)),
                ('is_active', models.BooleanField(default=False)),
                ('provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('suspension_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='EncryptedCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_password_encrypted', models.BinaryField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('ssl_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['status'], name='tenants_ten_status_e7eaee_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['tenant_code'], name='tenants_ten_tenant__62c292_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['hostname'], name='tenants_dom_hostnam_449a9c_idx'),
        ),
        migrations.AddConstraint(
            model_name='domain',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('tenant',), name='uniq_primary_domain_per_tenant'),
        ),
    ]
