# Generated by Django 5.2.17 on 2026-08-24 06:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legal_name', models.CharField(max_length=255)),
                ('trading_name', models.CharField(blank=True, max_length=255)),
                ('org_type', models.CharField(choices=[('SACCO', 'SACCO'), ('CHAMA', 'Chama'), ('MFI', 'Microfinance Institution'), ('LENDER', 'Lending Organization')], max_length=32)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(default='KE', max_length=2)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('kyc_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['org_type'], name='organizatio_org_typ_ac5ef8_idx'), models.Index(fields=['country'], name='organizatio_country_ae4420_idx')],
            },
        ),
    ]
