# Generated by Django 5.2.17 on 2026-08-24 06:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('STARTER', 'Starter'), ('GROWTH', 'Growth'), ('ENTERPRISE', 'Enterprise')], default='STARTER', max_length=16)),
                ('status', models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past Due'), ('CANCELED', 'Canceled')], default='TRIAL', max_length=16)),
                ('max_members', models.PositiveIntegerField(default=500)),
                ('max_branches', models.PositiveIntegerField(default=1)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='subscriptio_status_5e8870_idx'), models.Index(fields=['current_period_end'], name='subscriptio_current_e7d593_idx')],
            },
        ),
    ]
