# Generated by Django 5.2.17 on 2026-08-24 06:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_step', models.CharField(choices=[('VALIDATE', 'Validate'), ('CREATE_DB', 'Create Database'), ('CREATE_DB_USER', 'Create DB User'), ('GRANT_PERMISSIONS', 'Grant Permissions'), ('RUN_FINERACT_SCHEMA', 'Run Fineract Schema'), ('REGISTER_FINERACT_TENANT', 'Register Fineract Tenant'), ('SAVE_REGISTRY', 'Save Tenant Registry'), ('CREATE_ADMIN_USER', 'Create Admin User'), ('SEND_WELCOME_EMAIL', 'Send Welcome Email'), ('ACTIVATE', 'Activate Tenant'), ('DONE', 'Done')], default='VALIDATE', max_length=32)),
                ('is_success', models.BooleanField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=155)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provision_jobs', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'current_step'], name='provisionin_tenant__2ed0a0_idx')],
            },
        ),
    ]
